### ISSUE TITLE
Recurring dates for a period of time

### ISSUE THREAD

**Issue by McTom234** [hpi-schul-cloud/schulcloud-calendar#45]
Hey,
I am currently exploring the School Cloud Calendar. I noticed that one major feature is missing: You have to add repeating dates each time. It would be nice if you could add several dates for a certain period of time. For example, most mobile phone calendars offer this feature.

PS: I hope this is the right way to make the suggestion...

**Comment by janrenz** [comment]
HI, technically this is supported and already used. However afaik I think there is no support for this in the UI.
